// 50+ chains matching imToken supported networks
export const EVM_CHAINS = [
  { chainId: 1, name: 'Ethereum', symbol: 'ETH', rpcUrl: 'https://eth.llamarpc.com', explorerUrl: 'https://etherscan.io' },
  { chainId: 56, name: 'BNB Smart Chain', symbol: 'BNB', rpcUrl: 'https://bsc-dataseed.binance.org', explorerUrl: 'https://bscscan.com' },
  { chainId: 137, name: 'Polygon', symbol: 'POL', rpcUrl: 'https://polygon-rpc.com', explorerUrl: 'https://polygonscan.com' },
  { chainId: 42161, name: 'Arbitrum One', symbol: 'ETH', rpcUrl: 'https://arb1.arbitrum.io/rpc', explorerUrl: 'https://arbiscan.io' },
  { chainId: 10, name: 'Optimism', symbol: 'ETH', rpcUrl: 'https://mainnet.optimism.io', explorerUrl: 'https://optimistic.etherscan.io' },
  { chainId: 8453, name: 'Base', symbol: 'ETH', rpcUrl: 'https://mainnet.base.org', explorerUrl: 'https://basescan.org' },
  { chainId: 43114, name: 'Avalanche C-Chain', symbol: 'AVAX', rpcUrl: 'https://api.avax.network/ext/bc/C/rpc', explorerUrl: 'https://snowtrace.io' },
  { chainId: 250, name: 'Fantom', symbol: 'FTM', rpcUrl: 'https://rpc.ftm.tools', explorerUrl: 'https://ftmscan.com' },
  { chainId: 25, name: 'Cronos', symbol: 'CRO', rpcUrl: 'https://evm.cronos.org', explorerUrl: 'https://cronoscan.com' },
  { chainId: 100, name: 'Gnosis', symbol: 'xDAI', rpcUrl: 'https://rpc.gnosischain.com', explorerUrl: 'https://gnosisscan.io' },
  { chainId: 59144, name: 'Linea', symbol: 'ETH', rpcUrl: 'https://rpc.linea.build', explorerUrl: 'https://lineascan.build' },
  { chainId: 534352, name: 'Scroll', symbol: 'ETH', rpcUrl: 'https://rpc.scroll.io', explorerUrl: 'https://scrollscan.com' },
  { chainId: 324, name: 'zkSync Era', symbol: 'ETH', rpcUrl: 'https://mainnet.era.zksync.io', explorerUrl: 'https://explorer.zksync.io' },
  { chainId: 5000, name: 'Mantle', symbol: 'MNT', rpcUrl: 'https://rpc.mantle.xyz', explorerUrl: 'https://explorer.mantle.xyz' },
  { chainId: 81457, name: 'Blast', symbol: 'ETH', rpcUrl: 'https://rpc.blast.io', explorerUrl: 'https://blastscan.io' },
  { chainId: 1284, name: 'Moonbeam', symbol: 'GLMR', rpcUrl: 'https://rpc.api.moonbeam.network', explorerUrl: 'https://moonscan.io' },
  { chainId: 1285, name: 'Moonriver', symbol: 'MOVR', rpcUrl: 'https://rpc.api.moonriver.moonbeam.network', explorerUrl: 'https://moonriver.moonscan.io' },
  { chainId: 42220, name: 'Celo', symbol: 'CELO', rpcUrl: 'https://forno.celo.org', explorerUrl: 'https://celoscan.io' },
  { chainId: 1313161554, name: 'Aurora', symbol: 'ETH', rpcUrl: 'https://mainnet.aurora.dev', explorerUrl: 'https://aurorascan.dev' },
  { chainId: 1666600000, name: 'Harmony', symbol: 'ONE', rpcUrl: 'https://api.harmony.one', explorerUrl: 'https://explorer.harmony.one' },
  { chainId: 2222, name: 'Kava EVM', symbol: 'KAVA', rpcUrl: 'https://evm.kava.io', explorerUrl: 'https://kavascan.com' },
  { chainId: 66, name: 'OKX Chain', symbol: 'OKT', rpcUrl: 'https://exchainrpc.okex.org', explorerUrl: 'https://www.oklink.com/okc' },
  { chainId: 128, name: 'HECO', symbol: 'HT', rpcUrl: 'https://http-mainnet.hecochain.com', explorerUrl: 'https://hecoscan.io' },
  { chainId: 1088, name: 'Metis', symbol: 'METIS', rpcUrl: 'https://andromeda.metis.io/?owner=1088', explorerUrl: 'https://andromeda-explorer.metis.io' },
  { chainId: 288, name: 'Boba Network', symbol: 'ETH', rpcUrl: 'https://mainnet.boba.network', explorerUrl: 'https://bobascan.com' },
  { chainId: 1101, name: 'Polygon zkEVM', symbol: 'ETH', rpcUrl: 'https://zkevm-rpc.com', explorerUrl: 'https://zkevm.polygonscan.com' },
  { chainId: 7777777, name: 'Zora', symbol: 'ETH', rpcUrl: 'https://rpc.zora.energy', explorerUrl: 'https://explorer.zora.energy' },
  { chainId: 169, name: 'Manta Pacific', symbol: 'ETH', rpcUrl: 'https://pacific-rpc.manta.network/http', explorerUrl: 'https://pacific-explorer.manta.network' },
  { chainId: 204, name: 'opBNB', symbol: 'BNB', rpcUrl: 'https://opbnb-mainnet-rpc.bnbchain.org', explorerUrl: 'https://opbnbscan.com' },
  { chainId: 122, name: 'Fuse', symbol: 'FUSE', rpcUrl: 'https://rpc.fuse.io', explorerUrl: 'https://explorer.fuse.io' },
  { chainId: 8217, name: 'Klaytn', symbol: 'KLAY', rpcUrl: 'https://public-node-api.klaytnapi.com/v1/cypress', explorerUrl: 'https://scope.klaytn.com' },
  { chainId: 199, name: 'BitTorrent', symbol: 'BTT', rpcUrl: 'https://rpc.bittorrentchain.io', explorerUrl: 'https://bttcscan.com' },
  { chainId: 106, name: 'Velas', symbol: 'VLX', rpcUrl: 'https://evmexplorer.velas.com/rpc', explorerUrl: 'https://evmexplorer.velas.com' },
  { chainId: 61, name: 'Ethereum Classic', symbol: 'ETC', rpcUrl: 'https://etc.rivet.link', explorerUrl: 'https://blockscout.com/etc/mainnet' },
  { chainId: 888, name: 'Wanchain', symbol: 'WAN', rpcUrl: 'https://gwan-ssl.wandevs.org:56891', explorerUrl: 'https://wanscan.org' },
  { chainId: 10001, name: 'ETHW', symbol: 'ETHW', rpcUrl: 'https://mainnet.ethereumpow.org', explorerUrl: 'https://www.oklink.com/ethw' },
  { chainId: 1030, name: 'Conflux eSpace', symbol: 'CFX', rpcUrl: 'https://evm.confluxrpc.com', explorerUrl: 'https://evm.confluxscan.net' },
  { chainId: 592, name: 'Astar', symbol: 'ASTR', rpcUrl: 'https://evm.astar.network', explorerUrl: 'https://astar.subscan.io' },
  { chainId: 4689, name: 'IoTeX', symbol: 'IOTX', rpcUrl: 'https://babel-api.mainnet.iotex.io', explorerUrl: 'https://iotexscan.io' },
  { chainId: 9001, name: 'Evmos', symbol: 'EVMOS', rpcUrl: 'https://evmos-evm.publicnode.com', explorerUrl: 'https://escan.live' },
  { chainId: 7700, name: 'Canto', symbol: 'CANTO', rpcUrl: 'https://canto.slingshot.finance', explorerUrl: 'https://tuber.build/canto' },
  { chainId: 42262, name: 'Oasis Emerald', symbol: 'ROSE', rpcUrl: 'https://emerald.oasis.dev', explorerUrl: 'https://explorer.emerald.oasis.dev' },
  { chainId: 108, name: 'ThunderCore', symbol: 'TT', rpcUrl: 'https://mainnet-rpc.thundercore.com', explorerUrl: 'https://viewblock.io/thundercore' },
  { chainId: 40, name: 'Telos EVM', symbol: 'TLOS', rpcUrl: 'https://mainnet.telos.net/evm', explorerUrl: 'https://teloscan.io' },
];

export const NON_EVM_CHAINS = [
  { name: 'Bitcoin', symbol: 'BTC', rpcUrl: 'https://blockstream.info/api', explorerUrl: 'https://blockstream.info', family: 'btc' },
  { name: 'TRON', symbol: 'TRX', rpcUrl: 'https://api.trongrid.io', explorerUrl: 'https://tronscan.org', family: 'tron' },
  { name: 'TON', symbol: 'TON', rpcUrl: 'https://toncenter.com/api/v2/jsonRPC', explorerUrl: 'https://tonscan.org', family: 'ton' },
  { name: 'Cosmos Hub', symbol: 'ATOM', rpcUrl: 'https://cosmos-rpc.publicnode.com', explorerUrl: 'https://mintscan.io/cosmos', family: 'cosmos' },
  { name: 'Osmosis', symbol: 'OSMO', rpcUrl: 'https://osmosis-rpc.publicnode.com', explorerUrl: 'https://mintscan.io/osmosis', family: 'cosmos', prefix: 'osmo' },
  { name: 'Litecoin', symbol: 'LTC', rpcUrl: 'https://litecoinspace.org/api', explorerUrl: 'https://blockchair.com/litecoin', family: 'ltc' },
  { name: 'Dogecoin', symbol: 'DOGE', rpcUrl: 'https://dogechain.info/api/v1', explorerUrl: 'https://blockchair.com/dogecoin', family: 'doge' },
  { name: 'Bitcoin Cash', symbol: 'BCH', rpcUrl: 'https://blockchair.com/bitcoin-cash', explorerUrl: 'https://blockchair.com/bitcoin-cash', family: 'bch' },
  { name: 'Nervos', symbol: 'CKB', rpcUrl: 'https://mainnet.ckb.dev', explorerUrl: 'https://explorer.nervos.org', family: 'ckb' },
  { name: 'Filecoin', symbol: 'FIL', rpcUrl: 'https://api.node.glif.io', explorerUrl: 'https://filfox.info', family: 'fil' },
  { name: 'Tezos', symbol: 'XTZ', rpcUrl: 'https://mainnet.api.tez.ie', explorerUrl: 'https://tzkt.io', family: 'xtz' },
  { name: 'Polkadot', symbol: 'DOT', rpcUrl: '', explorerUrl: 'https://polkadot.subscan.io', family: 'dot' },
  { name: 'Kusama', symbol: 'KSM', rpcUrl: '', explorerUrl: 'https://kusama.subscan.io', family: 'ksm' },
  { name: 'Solana', symbol: 'SOL', rpcUrl: 'https://api.mainnet-beta.solana.com', explorerUrl: 'https://solscan.io', family: 'sol' },
  { name: 'Aptos', symbol: 'APT', rpcUrl: 'https://fullnode.mainnet.aptoslabs.com/v1', explorerUrl: 'https://explorer.aptoslabs.com', family: 'apt' },
  { name: 'Sui', symbol: 'SUI', rpcUrl: 'https://fullnode.mainnet.sui.io', explorerUrl: 'https://suiscan.xyz', family: 'sui' },
  { name: 'Near', symbol: 'NEAR', rpcUrl: 'https://rpc.mainnet.near.org', explorerUrl: 'https://nearblocks.io', family: 'near' },
  { name: 'Stellar', symbol: 'XLM', rpcUrl: 'https://horizon.stellar.org', explorerUrl: 'https://stellarchain.io', family: 'xlm' },
  { name: 'Ripple', symbol: 'XRP', rpcUrl: '', explorerUrl: 'https://xrpscan.com', family: 'xrp' },
];

// Deduplicate EVM by chainId
export const UNIQUE_EVM_CHAINS = EVM_CHAINS.filter(
  (c, i, arr) => arr.findIndex((x) => x.chainId === c.chainId) === i,
);
